#默认使用配置
#项目启动的时候也可以设置 Java -jar xxxxxx.jar spring.profiles.actiove=prod 也可以这样启动设置配置文件，但是这只是用于开发和测试。
spring:
  profiles:
    active: dev       #指定默认启动环境application-dev.yml
    include: redis    #引入文件application-redis.yml