#redis参数配置
spring:
  redis:
    password: 123456
    database: 0
    pool:
      jedis:
        max-active: 300
        max-wait: 500
        max-idle: 64
        min-idle: 8
    sentinel:
      nodes:
        - 192.168.165.200:16378
        - 192.168.165.200:26378
        - 192.168.165.200:36378
      master: master01